### ISSUE TITLE
Transaction not working properly with executeBulkInsertion

### ISSUE THREAD

**Issue by Abdullah-waqas** [ZiaDev/Pg-essential-dev#2]
When calling the executeTransaction function inside transaction callback, the client connection gets close. It should remain open to execute the rest of the queries

```
function transactionCallback{
let bulkData = [];
            for (let count = 0; count < 500; count++) {
                bulkData.push({
                    id: chance.guid(),
                    name: chance.name()
                });
            }
            const columns = ['id', 'name'];
            await client.executeBulkInsertion(bulkData, columns, 'test'); // client connection closes here
}
```

**Comment by ZiaDev** [comment]
Hi Abdullah thanks for your feedback. Actually the connections are not being managed by pg-essential package. 
You have to ensure it by your self that you are not closing the connection inside a transaction
